version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r lambda_function.zip index.py
      - echo Building Terraform configuration...
      - cd terraform
      - terraform init
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo Deploying Terraform changes...
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - lambda_function.zip
  discard-paths: yes
